name: Built Release

on:
  push:
    branches:
      - develop

jobs:
  built-release:
    uses: alleyinteractive/.github/.github/workflows/built-release.yml@main
    if: ${{ github.repository != 'alleyinteractive/create-wordpress-plugin' }}
    with:
      node: 16
      php: '8.2'
      github_token: ${{ secrets.GH_TOKEN }}
      composer_install: true
      draft: false
