name: Node Tests

on:
  pull_request:

jobs:
  npm-ci:
    name: (npm) Install, build, and test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node dependencies (npm ci)
        run: npm ci
      - name: Run npm lint
        run: npm run lint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
