name: PHP Coding Standards

on:
  pull_request:

jobs:
  phpcs:
    strategy:
      matrix:
        php: [ 8.0 ]
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: ${{ matrix.php }}
