name: PHP Coding Standards

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop
      - release/*

jobs:
  phpcs:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-composer-command.yml@main
    with:
      php: '8.3'
      command: |
        phpcs
