name: PHP Coding Standards
on:
  pull_request:
  workflow_dispatch:
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
      - name: Validate Composer package
        run: composer validate --strict
      - name: Install dependencies
        uses: ramsey/composer-install@v2
      - name: Run PHPCS
        run: composer phpcs
