name: PHP Coding Standards

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop

jobs:
  phpcs:
    strategy:
      matrix:
        php: [ 8.2 ]
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: ${{ matrix.php }}
