name: Testing Suite

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - develop

jobs:
  php-tests:
    strategy:
      matrix:
        multisite: [0, 1]
        php: ['8.2', '8.1', '8.0']
        wordpress: ["latest"]
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    with:
      command: "test"
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
