name: Testing Suite

on:
  pull_request:

jobs:
  php-tests:
    strategy:
      matrix:
        php: ['8.2', '8.1', '8.0', '7.4']
        wordpress: ["latest"]
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    with:
      command: "test"
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
